import StoreProvider from "./StoreProvider";
import AuthProvider from "./AuthProvider";
import './globals.css'
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { useEffect } from "react";
import { dispatch } from "d3";
import { fetchAllCompanyIds } from "../lib/features/company/companyAPI";
import { setCompanies } from "../lib/features/company/companySlice";
import { useAppDispatch } from "../lib/hooks/useAppDispatch";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <head>
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        />
      </head>
      <body>
        <AuthProvider>
          <StoreProvider>{children}</StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
